# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\designer.ui'
#
# Created by: PyQt5 UI code generator 5.15.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtGui import QIcon, QFont


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("BDWK.RedOrange")
        Form.resize(640, 435)
        self.radioButton = QtWidgets.QRadioButton(Form)
        self.radioButton.setGeometry(QtCore.QRect(60, 200, 51, 31))
        self.radioButton.setIconSize(QtCore.QSize(32, 32))
        self.radioButton.setObjectName("radioButton")

        self.radioButton_2 = QtWidgets.QRadioButton(Form)
        self.radioButton_2.setGeometry(QtCore.QRect(60, 260, 61, 41))
        self.radioButton_2.setIconSize(QtCore.QSize(32, 32))
        self.radioButton_2.setObjectName("radioButton_2")

        self.pushButton = QtWidgets.QPushButton(Form)
        self.pushButton.setGeometry(QtCore.QRect(390, 350, 121, 41))
        self.pushButton.setIconSize(QtCore.QSize(64, 64))
        self.pushButton.setObjectName("pushButton")
        self.label = QtWidgets.QLabel(Form)
        self.label.setGeometry(QtCore.QRect(20, 20, 60, 60))
        self.label.setObjectName("label")

        self.label_font = QtWidgets.QLabel(Form)
        self.label_font.setGeometry(QtCore.QRect(100, 10, 500, 60))
        self.label_font.setObjectName("label")

        self.textEdit = QtWidgets.QTextEdit(Form)
        self.textEdit.setGeometry(QtCore.QRect(150, 120, 431, 51))
        self.textEdit.setObjectName("textEdit")


        self.label_2 = QtWidgets.QLabel(Form)
        self.label_2.setGeometry(QtCore.QRect(60, 106, 101, 81))
        self.label_2.setObjectName("label_2")

        self.progressBar = QtWidgets.QProgressBar(Form)
        self.progressBar.setGeometry(QtCore.QRect(200, 230, 391, 31))
        self.progressBar.setProperty("value", 24)
        self.progressBar.setObjectName("progressBar")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "BDWK.RedOrange"))

        # Form.setToolTip(_translate("Form", "<html><head/><body><p><span style=\" font-size:14pt;\">RedOrange~</span></p></body></html>"))
        # self.radioButton.setText(_translate("Form", "Docx"))
        self.radioButton.setIcon(QIcon('imgs/文档.png'))
        # self.radioButton_2.setText(_translate("Form", "Pdf"))
        self.radioButton_2.setIcon(QIcon('imgs/PDF备份.png'))

        # self.pushButton.setText(_translate("Form", "Download"))
        # self.pushButton.setIcon(QIcon('imgs/下载01.png'))
        img = QtGui.QImage('imgs/下载.png')
        pixmap = QtGui.QPixmap(img)
        fitPixmap = pixmap.scaled(64, 64, QtCore.Qt.IgnoreAspectRatio,
                                  QtCore.Qt.SmoothTransformation)  # 注意 scaled() 返回一个 QtGui.QPixmap

        icon = QtGui.QIcon(fitPixmap)
        self.pushButton.setIcon(icon)

        self.label.setText(_translate("Form", "RedOrange_tools"))
        jpg = QtGui.QPixmap('imgs/logo.png').scaled(self.label.width(), self.label.height())
        self.label.setPixmap(jpg)

        self.label_font.setText(_translate("Form", "百度文库下载测试版~（08.26）"))
        self.label_font.setStyleSheet("color:rgb(175,233,221,250);font-size:36px;font-family:Microsoft YaHei;")
        # border-image: url(source/None.png);
        self.label_2.setText(_translate("Form", "TextLabel"))
        url_logo = QtGui.QPixmap('imgs/网站.png').scaled(self.label.width(), self.label.height())
        self.label_2.setPixmap(url_logo)

